"""empty message

Revision ID: 49ffa3afe9f7
Revises: 8af72b0dae6d
Create Date: 2025-10-07 15:12:12.110885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ffa3afe9f7'
down_revision = '8af72b0dae6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
